# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  api:
    image: sa-saopaulo-1.ocir.io/grbcvhus1oua/portfolio/api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - api/.env
    volumes:
      - /mnt/fs-core/apps/portfolio:/app/workdir
