# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db_tests:
    image: postgres:16
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  db_dev:
    image: postgres:16
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: de674b66bb1df188576a1a73770ea581aa48fae4
      POSTGRES_DB: portfolio

  app:
    build: .
    restart: always
    container_name: portifolio_api
    ports:
      - '3000:3000'
    env_file:
      - .env